[project]
name = "ci-sim"
version = "0.1.0"
description = "To be defined"
readme = "README.md"
authors = [
    { name = "Robim Ferreira", email = "fpgr07@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "python-json-logger>=4.2.0",
]

[project.scripts]
ci-sim = "ci_sim.__main__:_run"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.10",
]

[tool.ruff]
line-length = 80
lint.select = ["E", "F", "W", "I", "B", "UP", "G", "ARG", "PT"]